name: demo
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: shallow <775150@qq.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  proxiable:
    path: ../proxiable
  reflectable: any
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  build_runner: any
